language: python
python:
    - 2.7
    - pypy
install:
  - pip install coveralls
  - pip install -r requirements.txt
script: PYTHONPATH=$PYTHONPATH:. coverage run --source=html2text setup.py test -v
after_success: coveralls
